---

apiVersion: v1
kind: Service
metadata: 
  name: node
  namespace: default

spec: 
  ports: 
  - nodePort: 30003 #range is 30000- 
    port: 3000


    targetPort: 3000

  selector: 
    app: node # this label connects this service to deployment

  type: NodePort